# Generated by Django 4.1.7 on 2023-03-05 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='iha_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_code', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='iha_property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=200)),
                ('marka', models.CharField(default='BAYKAR', max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('agirlik', models.FloatField()),
                ('kategori', models.CharField(max_length=200)),
                ('tanim', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('iha_prdct', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='IhaApp.iha_product')),
            ],
        ),
    ]
