# Generated by Django 4.1.7 on 2023-03-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IhaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iha_product',
            name='model_code',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
