# Generated by Django 4.1.7 on 2023-03-05 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IhaApp', '0003_iha_product_created_at_iha_product_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iha_property',
            old_name='iha_prdct',
            new_name='iha_Product',
        ),
    ]
