# Generated by Django 4.1.7 on 2023-03-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IhaApp', '0004_rename_iha_prdct_iha_property_iha_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iha_property',
            name='kategori',
            field=models.CharField(choices=[('Keşif ve İstihbarat', 'Keşif ve İstihbarat'), ('Savunma', 'Savunma')], max_length=200),
        ),
    ]
